Fix bin/shly a little bit.

diff --git a/bin/shly b/bin/shly
--- a/bin/shly
+++ b/bin/shly
@@ -7,11 +7,6 @@ if [ -z "$SHELLY_HOME" ] || [ ! -f "$SHELLY_HOME/config" ]; then
     NOT_INSTALLED=1
 fi
 
-if [ "$DOWNLOADED" != 1 ] && [ "$NOT_INSTALLED" = 1 ] && [ "$1" != "install" ]; then
-    echo "Error: Shelly is not installed. If you wanna install it, run '$BASENAME install' first." 1>&2
-    exit 1
-fi
-
 ## Loading configurations
 
 retrieve_config_from_perl() {
@@ -264,7 +259,7 @@ load_core() {
 
 verbose="nil"
 
-if [ "$DOWNLOADED" = 1 ]; then
+if [ "$DOWNLOADED" = 1 ] && [ -z "$1" ]; then
     action="install"
     run_shelly_command "install" ":version" ":latest"
 fi
@@ -354,6 +349,12 @@ if [ -z "$action" ]; then
     help=1
     action="shelly::help"
     run_shelly_command "shelly::help"
+fi
+
+if [ "$DOWNLOADED" != 1 ] && [ "$NOT_INSTALLED" = 1 ] && [ "$action" != "install" ]; then
+    echo "Error: Shelly is not installed. If you wanna install it, run '$BASENAME install' first." 1>&2
+    echo "If you've already installed, reloading your *rc file would work." 1>&2
+    exit 1
 fi
 
 dumped_core_path=$(dumped_core_path)
